### PR TITLE
feat: chat message fetching pagination

### PR DESCRIPTION
**Pull request by brianp**
Description
---
Previously the only function to get messages was `get_all_messages` which return all related records in the db. Now we've added pagination and you can select the amount of results per page, and what page you'd like returned. Results are now ordered by most recent received.

Motivation and Context
---
`get_all_messages` has the potential to get very slow and ddos the client. Limiting the amount returned and allowing to change the requested amounts makes things better to deal with.

How Has This Been Tested?
---
Test added for pagination.

What process can a PR reviewer use to test or verify this change?
---
Tests pass.

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

### CODE REVIEW

**Comment by AaronFeickert** [comment]
I could see the following case occurring:
- The user requests the first page of messages and receives them.
- New messages arrive while the user is processing/reading/handling the first page.
- The user requests the second page of messages and receives them.
- The two pages overlap, but the user does not see the new messages.

This seems like it would make for irritating UX. How about adding an optional cursor that ensures that requests within the same "session" always maintain _consistent_ pagination? Then the user doesn't need to deduplicate messages. You could even add a simple function that informs the user if there exist messages newer than the cursor.

**Comment by brianp** [comment]
> This seems like it would make for irritating UX.

This happens to me on strava constantly

> How about adding an optional cursor that ensures that requests within the same "session" always maintain consistent pagination? Then the user doesn't need to deduplicate messages. 

I'll run it by the mobile team and see what they say, it's pretty much entirely for them.

**Comment by AaronFeickert** [comment]
> I'll run it by the mobile team and see what they say, it's pretty much entirely for them.

Could add it anyway, in case the feature is useful for others! The cursor could be entirely optional.

**Review by SWvheerden — APPROVED** [review]

**Comment by SWvheerden** [comment]
Cursor could be nice, but for a MvP which the whole chat FFI is, I think this is fine for now.

**Pull request merged**
