### PR TITLE
bump monero-rs dep to ^0.9.1

### LINKED ISSUE #2178: RUSTSEC-2020-0036: failure is officially deprecated/unmaintained
> failure is officially deprecated/unmaintained

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `failure`                      |
| Version             | `0.1.8`                   |
| URL                 | [https://github.com/rust-lang-nursery/failure/pull/347](https://github.com/rust-lang-nursery/failure/pull/347) |
| Date                | 2020-05-02                         |

The `failure` crate is officially end-of-life: it has been marked as deprecated
by the former maintainer, who has announced that there will be no updates or
maintenance work on it going forward.

The following are some suggested actively developed alternatives to switch to:

- [`anyhow`](https://crates.io/crates/anyhow)
- [`eyre`](https://crates.io/crates/eyre)
- [`fehler`](https://crates.io/crates/fehler)
- [`snafu`](https://crates.io/crates/snafu)
- [`thiserror`](https://crates.io/crates/thiserror)

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2020-0036.html) for additional details.

### PR DESCRIPTION
**Pull request by delta1**
## Description

Our upstream dependency on `monero` crate in the merge mining proxy was using the officially deprecated/unmaintained `failure` crate. [monero-rs/pull/20](https://github.com/monero-rs/monero-rs/pull/20) replaced `failure` with `thiserror`, and this PR updates our dependency to the new release of `monero`

## Motivation and Context

fixes #2178

## How Has This Been Tested?

all existing tests pass 

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [X] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [X] I'm merging against the `development` branch.
* [X] I ran `cargo-fmt --all` before pushing.
* [X] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by SWvheerden — DISMISSED** [review]
We might to bump this up shortly again:
https://github.com/monero-rs/monero-rs/pull/18

**Comment by delta1** [comment]
@SWvheerden good call, should I change this dep to ^0.9

@h4sh3d will the next release of monero-rs still be in the 0.9.x range?

**Comment by h4sh3d** [comment]
`monero` version 0.9.1 is now released!

**Comment by delta1** [comment]
Thanks @h4sh3d - you rule!

**Comment by delta1** [comment]
Bumped to ^0.9.1

**Review by SWvheerden — DISMISSED** [review]
LGTM

**Review by stringhandler — DISMISSED** [review]

**Comment by delta1** [comment]
PR_handler @mikethetike conflict resolved!

**Pull request merged**
