### PR TITLE
feat: timestamp validation

### PR DESCRIPTION
**Pull request by Cifko**
Description
---
Disable timestamp validation for orphan.
Enable during orphan new tips creation. It should be checked during the new tips creation so we don't select invalid tip in favor of lower difficulty but valid tip.

### CODE REVIEW

**Comment by stringhandler** [comment]
Related to #4870

**Review by stringhandler — COMMENTED** [review]
NACK. I don't think this is what @SWvheerden had in mind when logging the issue

**Review by SWvheerden — COMMENTED** [review]
utACK

I had an easier fix in mind with just not running this with the header validation. And only running this when we actually add the block, but this is fine. 

I do however want to test run this for a day to see if it works as intended.

**Comment by SWvheerden** [comment]
I did manage to sync one and tan through the night without any issues so far.

**Comment by Cifko** [comment]
I'm going through the code. And I don't see any validation of the median timestamp outside of the orphan tree construction. In the whole code we validate the median timestamp at two location, header sync and orphan tree construction. I can add the timestamp validation if the block added is not an orphan. But once we add anything from the stored orphan block there is no validation. Currently there is some validation that is not consistent across nodes.
When we decide that some orphan chain will be added we do only body validation. I can't find the header validation. Any tips where it is, or what direction should I take now?

**Comment by SWvheerden** [comment]
I would just add the check here:
https://github.com/tari-project/tari/blob/55d133494270fe92ab7cf48d58f18d2a2bdecd17/base_layer/core/src/validation/block_validators/body_only.rs#L58

This should be the last validator that's gets called right before a block is added to the database.

**Review by SWvheerden — COMMENTED** [review]
utACK

This is only done for block propagation and not syncing. 
But I think this should be fine as header sync will add and validate blocks in order. 

But perhaps just in terms of keeping header/block sync and block propagation validation in sync, we should make the the same changes there?

**Comment by Cifko** [comment]
> utACK
> 
> This is only done for block propagation and not syncing. But I think this should be fine as header sync will add and validate blocks in order.
> 
> But perhaps just in terms of keeping header/block sync and block propagation validation in sync, we should make the the same changes there?

Added. But IMHO I would not go this way. The sync has the validation in the headersync where it belongs. Now we do it double.

**Review by SWvheerden — COMMENTED** [review]
utACK

**Comment by sdbondi** [comment]
Yeah, agree with @Cifko, the async block validator does not need to validate headers, and that is efficiently done in the header sync by knowing that it will receive sequential headers. 

That said, the perf hit is minor so this could go in as is

**Review by stringhandler — DISMISSED** [review]
Can be merged once CI passes

**Review by sdbondi — DISMISSED** [review]

**Review by sdbondi — APPROVED** [review]

**Comment by sdbondi** [comment]
utACK

**Pull request merged**
