### PR TITLE
Ignore banned peers metadata during listening state

### PR DESCRIPTION
**Pull request by stringhandler**
## Description

Ignore banned peers during listening state. This should improve network stability as the node will not try to sync to a banned peer.

Also fix some formatting in the monero proof of work display
## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [ ] I'm merging against the `development` branch.
* [ ] I ran `cargo-fmt --all` before pushing.
* [ ] I ran `cargo test` successfully before submitting my PR.
* [ ] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by delta1** [comment]
Tests fail to compile, just needs an update in `base_layer/core/tests/node_state_machine.rs`

**Review by sdbondi — APPROVED** [review]
Think that there is a bug in liveness service - it should never include banned peers in the ping rounds. For now this can go in (untested), but I'll start working shortly on fixing that bug.

**Comment by stringhandler** [comment]
Is this still necessary with #2309 @sdbondi ?

**Comment by sdbondi** [comment]
@mikethetike In #2309 I couldn't see how banned peers could make it though (expected and acceptable race conditions aside). I've taken a look at the chain metadata service and I think that is where this issue should be solved. The chain metadata service should respond to `ConnectivityEvent::BannedPeer` by removing that peer from its internal collection. Almost done with the PR for that.

**Comment by sdbondi** [comment]
@mikethetike Think we can close this in favour of #2314

**Review by sdbondi — COMMENTED** [review]
@mikethetike Think we can close this in favour of #2314

**Pull request closed without merging**
