### PR TITLE
Add partial wallet backup for unencrypted wallet backup

### LINKED ISSUE #2009: Backend wallet backup and restore through CSV formatted data
The current method for wallet backup and restoration is for the mobile clients to do a full backup of the wallet sqlite db

When you backup the full sqlite db you backup the following:
- Comms private key
- Full transaction history (including pending transactions)
- All outputs (including invalid ones)
- Contacts

So the goal of producing a CSV export of the wallet is to try backup a minimal set of data that is compact as possible and then also be able to do backups as a series of diffs i.e. an initial backup which includes the once of Comms Private Key and then on subsequent request just what has changed.

## What is backed up

Can we confirm exactly what is going to go into the CSV formatted backup data:
- Optional Comms private key: This is optional to allow for unencrypted backups that only expose funds not identity.
- All completed transactions
- All valid outputs
- Contacts?

Do we want to include pending transactions?
Do we want to include invalid outputs that might become valid again? It is unlikely that this will happen ever but just checking.

## How the backup functionality will be used by the mobile client
The backup function can be called in two ways: 
1. A full backup will provide all the backup data in CSV form and will record the time at which the backup was made in the sqlite db.
2. A diff backup will provide only the data that is new since the last recorded backup call. If this is called with no initial full backup this will return the initial full backup

The restore function will accept multiple CSV formatted backup data batches which must include at least 1 initial full backup. The timestamps in the CSV data batches will be used to apply the initial backup and subsequent diffs in order.

If a restoration is done on a wallet that has existing data the backend will construct the DB view provided by the initial backup + subsequent diffs and then try merge that with the data that is currently in the sqlitedb.

### PR DESCRIPTION
**Pull request by philipr-za**
## Description
This PR adds functionality to produce a partial wallet backup that excludes the Comms Secret Key from the backup. This is to be used when the balance in a wallet is below a certain threshold so is low risk to backup without passphrase encryption. 

This use case is to allow for automatic backing up in the early use of the wallet while there are little funds so we don’t want to bother the nascent user with passphrase when the risk is low. When the funds are above a certain threshold an encryption passphrase would be required.

This PR adds:
- DB migration to store transaction direction for CompletedTransactions rather than relying on examining the Source Public Key. This is so that after a backup where the Private Key is cleared event though a new private key is generated the wallet can still tell which transactions were inbound or outbound.
- Functionality to perform the backup, clear the sensitive data and write it to the specified file.
- FFI interface to this functionality.

Restoration will be done by copying this backup file to the device and starting the wallet providing this db file as the database.

Because it is a Sqlite file and has the migration history inside it will automatically be migrated to new DB schema. When it is detected that there is no Comms Secret Key in the database a new one will be generated.

@kukabi @jasonvdb
There is a new FFI function that will need to be added to the wrapper but also I changed `wallet_is_completed_transaction_outbound(...)` to `completed_transaction_is_outbound(...)` as this check can now be done without needing to compare to the current Comms Public Key.

## Motivation and Context
Closes https://github.com/tari-project/tari/issues/2009

## How Has This Been Tested?
Tests provided to check the manual database migration logic.
Tests provided to exercise the backup process in the backend and in the FFI.

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [x] New Tests
* [ ] Documentation

## Checklist:

* [x] I'm merging against the `development` branch.
* [x] I ran `cargo-fmt --all` before pushing.
* [ ] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by CjS77** [comment]
LGTM, though there's a single clippy warning.

Note: libwallet based on this build will require a version bump.

**Comment by philipr-za** [comment]
Fixed the clippy stuff, including some other PR adjacent warnings.

**Comment by philipr-za** [comment]
> Note: libwallet based on this build will require a version bump.

Perhaps we should be using the FFI crate version to help with this?

**Review by CjS77 — APPROVED** [review]
lgtm

**Pull request merged**
