### PR TITLE
perf: switch to local-cache for self-hosted runners

### PR DESCRIPTION
**Pull request by CjS77**
We've switched out sccache for local-cache on the self-hosted runners. local-cache is a drop-in replacement for actions/cache, so this should be a very easy change to shave another 2-4 minutes off every PR CI run.

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

### CODE REVIEW

**Comment by CjS77** [comment]
ACK

**Comment by AaronFeickert** [comment]
Should approval of this PR be contingent on comparing its CI times to earlier PRs? Or is there enough variability that this wouldn't necessarily be useful?

**Comment by CjS77** [comment]
> Should approval of this PR be contingent on comparing its CI times to earlier PRs? Or is there enough variability that this wouldn't necessarily be useful?

It's basically guaranteed to be ±2-4min faster for self-hosted runs vs using actions/cache, since it does the same thing, but stores the cache on the local HDD rather than in the cloud

**Comment by AaronFeickert** [comment]
Maybe I'm misunderstanding what to expect from reported CI times, but looking at the [most recent](https://github.com/tari-project/tari/pull/5553/checks) PR that passes, the test job increased from 14 minutes to 29 minutes?

**Comment by CjS77** [comment]
Yes, because the 1st time you run with a new caching strategy you're definitely miss the cache, so it'll be a slow run.. and subsequent PRs will only use the local cache after the PR is merged

**Comment by AaronFeickert** [comment]
> Yes, because the 1st time you run with a new caching strategy you're definitely miss the cache, so it'll be a slow run

Ah, of course. Questions withdrawn :D

**Review by SWvheerden — APPROVED** [review]
Ack

**Comment by CjS77** [comment]
ACK

**Pull request merged**
