### PR TITLE
Base node displays status every 30 seconds

### PR DESCRIPTION
**Pull request by stringhandler**
Base node now prints out a general status message every 30 seconds. This can also be achieved via the `status` command. 

Also included was a refactor of the command execution from `Parser` into its own class `CommandHandler` to help with the futures and `mut`s that are required for the `select!`  in `cli_loop`

### CODE REVIEW

**Review by delta1 — APPROVED** [review]
LGTM - is there a way for the “listening status” to have the sync/tip info too? Would be nice to have

**Comment by stringhandler** [comment]
It shows the last block in the db which is pretty much the only data that's interesting in Listening status
`State: Listening, Tip: 18043 (Mon, 28 Dec 2020 16:17:09 +0000),`

**Comment by delta1** [comment]
Oh I missed that, nice!

**Comment by CjS77** [comment]
At some point the complexity of the command parser may benefit shifting to a purpose-written crate, e.g.

https://docs.rs/indicatif/0.15.0/indicatif/
and /or
https://github.com/phsym/shrust

But this is a step in the right direction so +1

**Review by CjS77 — APPROVED** [review]
LGTM

**Comment by stringhandler** [comment]
Those look amazing. Definitely keen to try them out at some point

**Pull request merged**
