### PR TITLE
feat: export transaction

### PR DESCRIPTION
**Pull request by SWvheerden**
Description
---
Exports a transaction from the wallet to a json file

Motivation and Context
---
This is the first step in allowing cold wallets to spend outputs while staying offline

How Has This Been Tested?
---
manual and unit test

### CODE REVIEW

**Review by hansieodendaal — COMMENTED** [review]
I cannot get this to work either by entering a command
```
minotari_console_wallet.exe --base-path . --command "export-tx 2444085111639818228 my_test_tx.txt"  --config %cd%\config\config.toml --log-config %cd%\config\log4rs_console_wallet.yml
```
or
```
minotari_console_wallet.exe --base-path . --command "export-tx --tx-id 2444085111639818228 --outfile my_test_tx.txt"  --config %cd%\config\config.toml --log-config %cd%\config\log4rs_console_wallet.yml
```
 or by passing  a script
```
export-tx 2444085111639818228 my_test_tx.txt
```
or 
```
export-tx --tx-id 2444085111639818228 --outfile my_test_tx.txt
```

**Comment by SWvheerden** [comment]
You have to run it with:
```
minotari_console_wallet --command-mode-auto-exit export-tx 17000381040930570644 --output-file pie.txt
```

**Comment by SWvheerden** [comment]
Running without file name to print to console
Screenshot 2024-02-02 at 13 58 03

**Comment by SWvheerden** [comment]
Running this:
```
./minotari_console_wallet  --command-mode-auto-exit export-tx 16507527571654191849 --output-file pie.txt
```
gives you this output:
```


⠀⠀⠀⠀⠀⣠⣶⣿⣿⣿⣿⣶⣦⣀                                                         
⠀⢀⣤⣾⣿⡿⠋⠀⠀⠀⠀⠉⠛⠿⣿⣿⣶⣤⣀⠀⠀⠀⠀⠀⠀⢰⣿⣾⣾⣾⣾⣾⣾⣾⣾⣾⣿⠀⠀⠀⣾⣾⣾⡀⠀⠀⠀⠀⢰⣾⣾⣾⣾⣿⣶⣶⡀⠀⠀⠀⢸⣾⣿⠀
⠀⣿⣿⣿⣿⣿⣶⣶⣤⣄⡀⠀⠀⠀⠀⠀⠉⠛⣿⣿⠀⠀⠀⠀⠀⠈⠉⠉⠉⠉⣿⣿⡏⠉⠉⠉⠉⠀⠀⣰⣿⣿⣿⣿⠀⠀⠀⠀⢸⣿⣿⠉⠉⠉⠛⣿⣿⡆⠀⠀⢸⣿⣿⠀
⠀⣿⣿⠀⠀⠀⠈⠙⣿⡿⠿⣿⣿⣿⣶⣶⣤⣤⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⡇⠀⠀⠀⠀⠀⢠⣿⣿⠃⣿⣿⣷⠀⠀⠀⢸⣿⣿⣀⣀⣀⣴⣿⣿⠃⠀⠀⢸⣿⣿⠀
⠀⣿⣿⣤⠀⠀⠀⢸⣿⡟⠀⠀⠀⠀⠀⠉⣽⣿⣿⠟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⡇⠀⠀⠀⠀⠀⣿⣿⣿⣤⣬⣿⣿⣆⠀⠀⢸⣿⣿⣿⣿⣿⡿⠟⠉⠀⠀⠀⢸⣿⣿⠀
⠀⠀⠙⣿⣿⣤⠀⢸⣿⡟⠀⠀⠀⣠⣾⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⡇⠀⠀⠀⠀⣾⣿⣿⠿⠿⠿⢿⣿⣿⡀⠀⢸⣿⣿⠙⣿⣿⣿⣄⠀⠀⠀⠀⢸⣿⣿⠀
⠀⠀⠀⠀⠙⣿⣿⣼⣿⡟⣀⣶⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⡇⠀⠀⠀⣰⣿⣿⠃⠀⠀⠀⠀⣿⣿⣿⠀⢸⣿⣿⠀⠀⠙⣿⣿⣷⣄⠀⠀⢸⣿⣿⠀
⠀⠀⠀⠀⠀⠀⠙⣿⣿⣿⣿⠛⠀                                                          
⠀⠀⠀⠀⠀⠀⠀⠀⠙⠁⠀                                                            
Console Wallet

Enter wallet passphrase: 
Feb 02 14:00:08.355 [warn] Fixing permissions on directory /var/folders/47/s77gktfj4gj65ddlms6xrghm0000gn/T/.tmpSWt9cV
Minotari Console Wallet running... (Command mode started)
==============
Command Runner
==============

1. ExportTx(ExportTxArgs { tx_id: 16507527571654191849, output_file: Some("pie.txt") })

Minotari Console Wallet running... (Command mode completed)

Shutting down wallet... Done.
```
And creates this file:

[pie.txt](https://github.com/tari-project/tari/files/14139690/pie.txt)

**Review by hansieodendaal — APPROVED** [review]
ACK

**Comment by hansieodendaal** [comment]
I tested the wrong exe, sorry about that

**Pull request merged**
