### PR TITLE
feat: console wallet use dns seeds

### PR DESCRIPTION
**Pull request by SWvheerden**
Description
---
Console wallet use dns seeds

Motivation and Context
---
The console wallet should use the DNS seed, and not just the seeds in the config file 

How Has This Been Tested?
---
Manual

### CODE REVIEW

**Comment by stringhandler** [comment]
Nice find

**Review by brianp — COMMENTED** [review]
I think I want to test this.

but a clarification if you will:

> should use the DNS seed, and not just the seeds in the config file

> *and not just*

So it should use both? Because the change swings the pendulum, to ignore the config seeds, and use whatever the PeerDB already has.
At what point did it fetch DNS seeds?

**Comment by SWvheerden** [comment]
> > ld use the DNS seed, and not just the seeds in the config file
> 
> > _and not just_

it should use both:

https://github.com/tari-project/tari/blob/851cb0070f057399d128df37970916250a5cf1ec/base_layer/p2p/src/initialization.rs#L583

**Review by brianp — APPROVED** [review]
LGTM

Thanks for the response.

Tested locally:
Created new wallet on esme network. Removed the peers from the config. Deleted the dht, and peer db. Restarted the wallet and it started finding peers instantly, found and connected to a base node, and carried on.

👍🏻 

Ack (sans ut)

**Pull request merged**
