### PR TITLE
ci: add auto labeler for clippy

### PR DESCRIPTION
**Pull request by sdbondi**
Description
---
Adds `workflow_run` trigger that adds/removes "clippy failed" label depending on "Clippy check" step

Motivation and Context
---
Easier to tell at a glance of the PR list if clippy has failed

How Has This Been Tested?
---

### CODE REVIEW

**Review by stringhandler — DISMISSED** [review]
lol, nice

**Comment by sdbondi** [comment]
Going to try it out first and see if it works :)

**Comment by sdbondi** [comment]
Eh well, not sure of it works. May require this PR to be merged before it can trigger a workflow outside of the PR - not sure if this feature is worth the effort

**Review by stringhandler — APPROVED** [review]

**Comment by sdbondi** [comment]
@mikethetike I think merge queue doesn't like merging CI changes? Maybe need a squash merge

**Pull request merged**
