### PR TITLE
Prevent loop in peer sync by storing all peers attempted

### PR DESCRIPTION
**Pull request by stringhandler**
## Motivation and Context

Using 3 base nodes, I found that the one node would hit 100% cpu. This was caused by it trying to sync peers with one peer and then the other peer in an infinite loop. The attempt here is to store all peers attempted in a single place. 

I think a better solution in future would be to store the last_peer_sync_succeeded time in the peer database so that it isn't retried again.

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [ ] I'm merging against the `development` branch.
* [ ] I ran `cargo-fmt --all` before pushing.
* [ ] I ran `cargo test` successfully before submitting my PR.
* [ ] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by hansieodendaal** [comment]
Running two tests: sync from scratch and sync from ~1000 blocks behind, both without pruning.

**Comment by hansieodendaal** [comment]
**Question:** With selecting random sync peers from `all_attempted_peers` instead of `previous_sync_peers`, will it not result in random peers being selected for sync that is not available?

**Comment by stringhandler** [comment]
The `all_attempted_peers` are passed into the `exclude_peers` parameter, so they are excluded and not tried again

**Comment by hansieodendaal** [comment]
1. `sync from scratch` did not work due to different unrelated error:
```
[c::bn::state_machine_service::states::block_sync] WARN  Banning all peers from local node, because they 
could not provide a valid chain link
```
2. sync from ~1000 blocks behind worked fine

**Note:** I think test case 1 should also pass when that problem is fixed.

**Review by hansieodendaal — APPROVED** [review]
LGTM, both sync test cases succeeded.

**Pull request merged**
