### PR TITLE
fix: wallet always scan interactive payments (see #4452)

### PR DESCRIPTION
**Pull request by jorgeantonio21**
Description
--- Wallet should always scan for interactive payments.

Motivation and Context
--- See issue #4452.

How Has This Been Tested?
--- Unit tests

### CODE REVIEW

**Review by sdbondi — DISMISSED** [review]
Tested this with 2 wallets, same pk different tor, and apart from the wallets kicking each other off the network, the scanning now picks up standard outputs successfully

**Comment by SWvheerden** [comment]
Fixes: https://github.com/tari-project/tari/issues/4452

**Comment by SWvheerden** [comment]
This looks good, just fix that log entry in `standard_outputs_recoverer.rs` ln 158

**Comment by jorgeantonio21** [comment]
> This looks good, just fix that log entry in `standard_outputs_recoverer.rs` ln 158

@SWvheerden, I removed the log

**Review by SWvheerden — APPROVED** [review]
LGTM

**Review by sdbondi — APPROVED** [review]

**Pull request merged**
