### PR TITLE
[wallet] Allow transactions to send to self

### PR DESCRIPTION
**Pull request by sdbondi**
## Description

Allow wallet to create and broadcast transactions to self.

- Add call to transaction service that creates and broadcasts the transaction
- Add TransactionCompletedImmediately event and hooked that up to console wallet UI
- Minor optimisations (unnecessary clones, early loop exit)

## Motivation and Context

Currently, transactions sent to self stay in pending forever as p2p negotiation cannot occur.
This PR detects and handles this case by instantly creating and broadcasting the transaction.

## How Has This Been Tested?

1 Functional and 1 Integration test. Tested manually in console wallet.

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [ ] I'm merging against the `development` branch.
* [ ] I ran `cargo-fmt --all` before pushing.
* [ ] I ran `cargo test` successfully before submitting my PR.
* [ ] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by delta1 — DISMISSED** [review]
Looks really good. I haven't tested, but I wonder if `select_utxos` should be modified to also return the total value of utxos selected, since any callers are probably going to want that info?   Anyway that could be a separate PR. Nice one!

**Review by philipr-za — DISMISSED** [review]
LGTM

**Comment by delta1** [comment]
Tested, working well - the console wallet just needs an update in the wallet event monitor to listen for `TransactionCompletedImmediately` and trigger a state refresh so it displays the tx immediately.

**Comment by sdbondi** [comment]
@delta1 Nice catch - pushed an update

**Review by delta1 — APPROVED** [review]
LGTM

**Pull request merged**
