### PR TITLE
[chore] Remove the text_message_service from the wallet

### PR DESCRIPTION
**Pull request by philipr-za**
## Description
The text_message_service was an idea in the very early days of the code base and it was put on hold so it was just commented out but the code base has moved on significantly and it was never removed.

This PR axes it finally.

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [x] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [x] I'm merging against the `development` branch.
* [x] I ran `cargo-fmt --all` before pushing.
* [x] I ran `cargo test` successfully before submitting my PR.
* [x] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by sdbondi — APPROVED** [review]
bye bye code

**Review by SWvheerden — APPROVED** [review]
LGTM
Although I personally think having a text message service in aurora will be great and of benefit, it's currently not used there. And this code is not lost forever

**Comment by philipr-za** [comment]
> LGTM
> Although I personally think having a text message service in aurora will be great and of benefit, it's currently not used there. And this code is not lost forever

It's also from the first days of the wallet so is like two refactors and architecture updates old so would have to reimplement anyway.

**Comment by delta1** [comment]
> And this code is not lost forever

It's always still available in Git. I'm a big fan of getting rid of code that's unused. +1 LGTM

**Pull request merged**
