### PR TITLE
chore: upgrade tonic and prost

### PR DESCRIPTION
**Pull request by brianp**
Description
---
We were hoping to get moved onto a more modern version of both but this will not be possible. Between versions 0.8.4 and 0.9.0 of tonic they dropped support for the rust 2018 version. We would also need to upgrade to 2021 to make further use of more recent versions of tonic.

This PR upgrades them to the most recent possible.

I additionally tried seeing if we could run older versions only _where nedded_ and run more modern version in other places but most of our tonic use is tied to the grpc and the grpc clients require the older version, in turn most everything requires the old version.

Motivation and Context
---
Upgrade the old to something newer.

How Has This Been Tested?
---
CI

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

### CODE REVIEW

**Comment by brianp** [comment]
I can't figure out how to silence clippy with proto files. I tried both:

```
#![allow(clippy::all)]
#[allow(clippy::all)]
```

**Comment by AaronFeickert** [comment]
Looks like the lints are `pedantic`, which isn't included in `clippy::all`. [This source](https://stackoverflow.com/questions/74977003/how-to-prevent-cargo-clippy-from-analyizing-generated-prost-files) suggests using `#![allow(clippy::all, clippy::pedantic)]` should work.

**Comment by brianp** [comment]
@AaronFeickert lol *all* but not everything 🙃

**Review by SWvheerden — APPROVED** [review]

**Comment by AaronFeickert** [comment]
> @AaronFeickert lol _all_ but not everything 🙃

\* some restrictions apply

**Pull request merged**
