### PR TITLE
Create a Flaky Tests Feature to identify tests that occasionally fail 

### PR DESCRIPTION
**Pull request by mikethetike**
## Description

I created a feature to mark tests that fail from time to time. This helps new developers know if tests that are failing locally or on the CI server need to be fixed. Ideally all tests should pass consistently, so it also points out new "Good first issues" for people joining the project.

I also altered the Circle CI process so that the `flaky-tests` feature is not run on the debug test run. Unfortunately cargo doesn't have a way of excluding specific features on tests, so I had to use `--all-features`. This means that any test that is under a non-default feature will not be run if `include-flaky-tests` is false (Circle CI).

The flaky tests will still be run on the release test run on Circle CI

A test can be marked flaky by adding the `cfg` attribute
```
#[test]
#[cfg(feature="flaky-tests")]
fn test_forked_block_sync() {
```

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [ ] I'm merging against the `development` branch.
* [ ] I ran `cargo-fmt --all` before pushing.
* [ ] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by CjS77** [comment]
Could this not be handles with `#[ignore]`?
https://doc.rust-lang.org/book/ch11-02-running-tests.html#ignoring-some-tests-unless-specifically-requested

**Comment by SWvheerden** [comment]
we should be able to ignore them. 
but I wonder if we should not ignore them for now and try to spend time to fix them rather.

**Comment by mikethetike** [comment]
While the effect is the same as running `cargo test -- --ignored` it is quite different in semantics:

1. If a test is marked as `ignored` it can mean any of:
  - This test is not finished
  - This test was working but has been broken recently and there isn't time to fix it
  - The test sometimes works
  - The test was temporarily ignored to get it through CI
2. The reason is not clear why it has been ignored. By creating a feature you can group tests together in a way that conveys why they are flaky/intermittent. You can certainly add comments to each test why it has been ignored, but you cannot see them as a group.
3. By having a feature, you could retry flaky tests multiple times on a CI server before failing them
4. These tests should be run on every CI cycle, even if some of them fail. To do the same with `#ignore` you would have to run all ignored tests each time. This means you cannot use ignore for any of the reasons in 1.

Lastly, IMHO it's intuitive to run `cargo test --all-features` whereas it's not intuitive that `cargo test -- --ignored` should be run.

**Comment by mikethetike** [comment]
Tests seem to be passing more regularly now, so doesn't look like this is still necessary

**Pull request closed without merging**
