### PR TITLE
WIP RFC Multi party utxo

### PR DESCRIPTION
**Pull request by SWvheerden**
## Description
This is work in progress RFC. 
The following is still required:
- Bulletproof explanation
- RFC number

## Motivation and Context
We require multi party UTXO's in tari

## Types of changes
* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [x] Documentation

## Checklist:
* [x] I'm merging against the `development` branch
* [x] I ran `cargo-fmt --all` before pushing
* [ ] My change requires a change to the documentation.
* [x] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by SWvheerden** [comment]
Yes as I said above this still needs the bulletproof construction as this requires a non normal setup. But I do agree that I think we should add an examples of how to create and spend that. The spending is a normal transaction, but writing it out will prove and make that clear.

**Comment by hansieodendaal** [comment]
Maybe this could work, an alternative to Grin's method. (I know, some explaining will be necessary :-))

multi-party-coloured-utxo-concept-a (1)

**Comment by hansieodendaal** [comment]
See development of [Mimblewimble Multiparty Bulletproof UTXO](https://github.com/tari-labs/tari-university/tree/mw-multiparty-bulletproof-utxo/src/protocols/mimblewimble-mp-bp-utxo) in TLU. When done, we should be able to '_RFC-0230_HTLC_' and reference the applicable bits.

**Comment by hansieodendaal** [comment]
See https://github.com/tari-labs/tari-university/pull/179. I propose that after that report has been published on TLU we decide if we need this RFC and how to update '_RFC-0230_HTLC_' .

**Pull request merged**
