### PR TITLE
ASCII table output for list-peers and list-connections

### PR DESCRIPTION
**Pull request by sdbondi**
## Description

- Added basic ASCII table implementation that is easy to copy into a
      spreadsheet
    - `list-peers` and `list-connections` use table implementation
    - `list-connections` shows peer data and duration of connection

```
NodeId           | Public Key                                                       | Address                                                                | Direction | Uptime  | Role
75cfb63f1e967a5d | 2e93c460df49d8cfbbf7a06dd9004c25a84f92584f7d0ac5e30bd8e0beee9a43 | /ip4/127.0.0.1/tcp/60187                                               | Inbound   | 13m 38s | Base node
9fc307fd4c4874fd | b81b4071f72418cc410166d9baf0c6ef7a8c309e64671fafbbed88f7e1ee7709 | /ip4/127.0.0.1/tcp/60176                                               | Inbound   | 13m 39s | Base node
099fc6fc362f07b5 | 3a5081a0c9ff72b2d5cf52f8d78cc5a206d643259cdeb7d934512f519e090e6c | /ip4/127.0.0.1/tcp/60169                                               | Inbound   | 13m 41s | Base node
609e2f8272a22c76 | ee445a2a74b1acd85c69af2880c2341ece651ac3b7ca36370df695f6faf62b4e | /onion3/zkai65rsht26si35xgezkc2kh3dkr72v2723efpy444ds45kr62imaid:18141 | Outbound  | 13m 35s | Base node
4 active connection(s)
```

## Motivation and Context

Ugly hard-to-read output for `list-peers` and `list-connections`. `list-connections` only displayed the peer node ID which made it difficult to determine which peers are connected.

~~New dependency on tari_base_node: `prettytable-rs`~~

### CODE REVIEW

**Comment by CjS77** [comment]
TBH, it would be handier if the data was CSV or formatted in a way that made putting it into a spreadsheet easier

**Comment by sdbondi** [comment]
Cool, makes sense for `list-peers` - What about `list-connections`?

**Comment by hansieodendaal** [comment]
This works fine on Windows as well.

**Comment by hansieodendaal** [comment]
> TBH, it would be handier if the data was CSV or formatted in a way that made putting it into a spreadsheet easier

I agree. Maybe it would make sense to have it delimited with commas, aligned and displayed in columns, but without the extra table border characters.

**Comment by sdbondi** [comment]
Ye agree, the borders are actually a bit much - using pretty tables was just quicker to do last night and is definitely an improvement to what was there - we can put always put this on hold for now and take a look again when I get time

**Comment by CjS77** [comment]
You know what, if we dropped the horizontal dividers, we'd still get nice looking tables and could use `|` as the separator when importing into spreadsheets.

**Pull request merged**
