### PR TITLE
Add DNS seed support in base node

### LINKED ISSUE #2311: Tracking issue: DNS seeds support for Tari applications
Tracking issue for DNS seeds support for Tari applications.

## Tasks

- [x] Create resolver and parser for Tari seed peer DNS TXT entries (PR #2319)
- [ ] ~~tari_comms needs to be able to connect to a peer and obtain the public key given only the address~~
- [ ] DNS records and peers must be resolved on node / wallet startup (PR #2352)
- [ ] Comms integration (PR #2352)
- [ ] Allow DNS seeds to be configured from toml config (PR #2352)
- [ ] Support for DNSSEC (PR #2352)

### PR DESCRIPTION
**Pull request by sdbondi**
## Description

- DNS seed hosts can be added in base node configuration
  (`base_node.mainnet|rincewind.dns_seeds`)
- DNS seeds are resolved and added to the peer list on startup
- DNSSEC support and enabled by default (`dns_seed_use_dnssec` config)
- Name server can be specified for DNS seed resolution
  (`dns_seed_name_server`). Default is `1.1.1.1:53` (cloudflare)
- Moved seed_peers into `CommsConfig`.
- Replaced parse_seed_peers utility function with `SeedPeer::from_str` impl 

## Motivation and Context

Closes #2311 
Ref #2319

## How Has This Been Tested?

Some unit tests. Manual testing on base node.

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [x] New Tests
* [ ] Documentation

## Checklist:

* [x] I'm merging against the `development` branch.
* [x] I ran `cargo-fmt --all` before pushing.
* [ ] I ran `cargo test` successfully before submitting my PR.
* [x] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by delta1** [comment]
Hey @sdbondi it seems there are missing imports in `applications/tari_app_utilities/src/utilities.rs`

**Comment by sdbondi** [comment]
@delta1 Dang, bad rebase - will fix now

**Comment by delta1** [comment]
Checking it out now, this looks awesome 👏 

Flaky test failed on circleci - but all tests passed on my local machine. 

Please add the new config items to `tari_config_sample.toml` and `windows.toml`

**Review by delta1 — DISMISSED** [review]
Really great work! Tested successfully. LGTM

**Comment by delta1** [comment]
I think your dnssec update needs to get added to the tests @sdbondi 

```
 --> base_layer/wallet/tests/wallet/mod.rs:97:24
   |
97 |     let comms_config = CommsConfig {
   |                        ^^^^^^^^^^^ missing `dns_seeds_use_dnssec`
```

**Comment by sdbondi** [comment]
@delta1 Fixed - wow, those configs in tests everywhere really need to be DRY'd up 😄

**Review by delta1 — DISMISSED** [review]
LGTM

**Comment by delta1** [comment]
hey @sdbondi there seems to be a compilation error when running `cargo test` 

```
error[E0601]: `main` function not found in crate `pingpong`
 --> base_layer/p2p/examples/pingpong.rs:1:2
  |
1 |
  |  ^ consider adding a `main` function to `base_layer/p2p/examples/pingpong.rs`

```

I'm guessing that file was deleted but maybe got reintroduced when fixing merge conflicts

**Comment by sdbondi** [comment]
Thanks @delta1  - fixed

**Review by stringhandler — APPROVED** [review]

**Pull request merged**
