### PR TITLE
Add better error messages for LMDB

### PR DESCRIPTION
**Pull request by mikethetike**
## Description

On windows if you run tari_base_node with an LMDB size too large, you get this error:

```
 [base_node::app] ERROR critical error
```

I updated some of the errors so that a more meaningful error is displayed:
```
ERROR Could not create LMDB store:An LMDB error occurred:There is not enough space on the disk.
```

The `derive_error` crate has very limited capabilities for formatting errors, so I added `quick_error` which gives much more control over getting the underlying error. `quick_error` also seems to be more maintained than `derive_error`

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [x] I'm merging against the `development` branch.
* [x] I ran `cargo-fmt --all` before pushing.
* [x] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by CjS77** [comment]
Is the log target lost in the new message?

**Comment by mikethetike** [comment]
No, I just didn't copy it

**Comment by CjS77** [comment]
I think the larger issue here is -- do we want to move to a new error handling crate?
In which case, let's change once and not have to migrate again in 6 months.

I came across this discussion recently: https://www.reddit.com/r/rust/comments/feynbz/what_is_a_recommended_crate_for_defining_errors/

And this:
https://www.reddit.com/r/rust/comments/dfkwfo/announcing_thiserror_a_convenient_modern/
which had this comment:

> I understand the history of error handling evolution, like (at least this is how I see it)
```
quick-error
  |
  V
error-chain
  |
  V
failure ---> snafu (should it be here or somewhere else?)
  |
  V
extending std::error::Error
  |
  V
anyhow + thiserror
```

which all leads to suggest (based on 15min of searching) that `thiserror` may be approach with more longevity?

**Comment by dunnock** [comment]
I agree about thiserror + anyhow combination. Anyhow has survived time check already and thiserror is young but it's building on top of that.

I used anyhow as it allows casting of various external and internal error types automatically, so that code can throw any kind of error and ? will just cast them automatically. It's cool that thiserror allows to embed and cast any error into your type too:
```
#[derive(Error, Debug)]
pub enum MyError {
    ...

    #[error(transparent)]
    Other(#[from] anyhow::Error),  // source and Display delegate to anyhow::Error
}
```

Just for information, there is another approach which boat-guy recently suggested https://boats.gitlab.io/blog/post/failure-to-fehler/ - worth reading, but it's too radical for Rust IMHO so might not survive..

**Comment by CjS77** [comment]
@mikethetike what do you think about switching to thiserror rather than quick-error for this PR?

**Comment by mikethetike** [comment]
Will look into thiserror. I chose quickerror mainly because it had the most downloads (400k) after `failure` (which I don't think is revelant anymore), and also because of the flexibility of handling the error conversion. I also like the `context` function, which is what I liked about `snafu`, so it's my now preference for errors. But I'm happy to try out `thiserror` and see if it takes the top spot.

**Comment by mikethetike** [comment]
Moved over to `thiserror`. Pretty much the same as `quick-error`. I updated the ChainStorageError as well. Not sure if that's what you intended. 

It's pretty tough to reproduce all of the errors, but this is what the LMDB one looks like now:
```
[base_node::app] ERROR There appears to be a critical error on the back end:Could not create LMDB store:An LMDB error occurred:There is not enough space on the disk.
. Check the logs for more information.
```

Note: I removed the comment saying that the database might be corrupted, since that could actually happen anywhere and you should know for certain before alarming users. I can put it back if you want

**Comment by CjS77** [comment]
I think we're good. 

Excellent; I think we can start the long and painful process of migrating all errors from derive-error to thiserror/anyhow

**Pull request merged**
