### PR TITLE
[ci] Optimize CI

### PR DESCRIPTION
**Pull request by stringhandler**
Optimize CI process:
1. Remove `cargo fmt` checks from other steps. It is currently already done by the clippy check
~~2. Tests are not run in release mode, hopefully this speeds up compile time~~
3. Pre-compile binaries for cucumber tests  
4. Formatted Cucumber scenarios

### CODE REVIEW

**Comment by delta1** [comment]
1. Looks good
2. The tests were already being compiled in release? From what I can see [here](https://app.circleci.com/pipelines/github/tari-project/tari/10604/workflows/f82050ae-51fd-4416-b2ec-79d32a1778fd/jobs/27397): `cargo test --workspace --all-features --jobs=3 --release` 
3. Looks like the integration tests run OOM. 

LGTM in general, this CI run had weird failures in build and test so maybe just re-trigger it. 

PS: love the branch name 😆

**Comment by delta1** [comment]
Looks like I had the same CI build and test failures with this setup, so I don't think it's working as expected

**Comment by stringhandler** [comment]
Thanks, w.r.t to 2, I had tried to test in debug mode, which still fails, so put them back in release mode

**Comment by stringhandler** [comment]
Closing and re-opening on the main fork to test CI better

**Pull request closed without merging**
