### PR TITLE
Added a currency style formatter for T and µT

### PR DESCRIPTION
**Pull request by Krakaw**
I have added a formatter to split values of T or µT every 3 places from the end of the whole number. The decimal places of T has been limited to 2.
image
image
image

## Description

Refactored the `Display` implementation for `Tari` and `MicroTari` to use the new helper function `display_currency` 
## Motivation and Context

Distinguishing between millions or tens of millions of µT / T was getting painful.
## How Has This Been Tested?

Updated the tests to include the new formatting as well as a few examples of the rounding.
## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [x] I'm merging against the `development` branch.
* [x] I ran `cargo-fmt --all` before pushing.
* [x] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by Krakaw** [comment]
Tests passed locally ¯\_(ツ)_/¯

**Comment by Krakaw** [comment]
Nice spot! Added it to the tests.

**Comment by CjS77** [comment]
I like the currency formatting and would like to keep it, but I have concerns about making it the default `Display` impl. 

My worry is that you can't copy tari values anymore, or double-click select  and so on, so while it looks nice, it may hurt utility.

**Comment by Krakaw** [comment]
Yeah I was considering implementing the new functionality under `Debug` instead. Then we can choose where to output the currency formatted values.

**Comment by CjS77** [comment]
How's this:
1. Keep current `MicroTari` `Display` as is (for now, but could revert back to straight up int / f64)
2. Create new struct `FormattedMicroTari` that wraps a `u64`, `impl`s `From <MicroTari>` and has `Display` as you've proposed here.
3. Add `formatted(self) -> FormattedMicroTari` method to `MicroTari`

Sounds win-win to me. Displaying the formatted result is only a little bit of extra typing:

`debug!("You have a balance of {}", amount.formatted()"`

**Pull request merged**
