### PR TITLE
test: fix tests to run standalone in wallet

### PR DESCRIPTION
**Pull request by stringhandler**
Allow tests to be run individually, i.e. `cargo test -p tari_wallet` in the wallet.

The main reason this didn't work was that the wallet excluded the `base_node` feature from `tari_core`. I've added it as a dev-dependency, but not sure if it breaks the libwallet build

### CODE REVIEW

**Comment by AaronFeickert** [comment]
Tested manually, and this fix appears to work for individual wallet tests. Have not tested any other build consequences.

**Comment by sdbondi** [comment]
Unfortunately it appears that rust still has the issue where it uses features from dev dependencies in release builds.
Tested with `cargo build --package tari_wallet --release` and croaring is included in the build.

I think the following works in tari_core/lib.rs:

```rust
#[cfg(feature = "base_node")]
mod domain_hash {
    use tari_crypto::{hash::blake2::Blake256, hash_domain, hashing::DomainSeparatedHasher};
    use tari_mmr::{pruned_hashset::PrunedHashSet, Hash, MerkleMountainRange, MutableMmr};

    hash_domain!(
        KernelMmrHashDomain,
        "com.tari.tari_project.base_layer.core.kernel_mmr",
 // (snip..)
}
#[cfg(feature = "base_node")]
pub use domain_hash::*;
```

**Comment by AaronFeickert** [comment]
Any manual tests/processes that should be run to confirm this works as expected?

**Comment by stringhandler** [comment]
@AaronFeickert I need to fix the CI jobs

**Pull request merged**
