### PR TITLE
[Mining Node] Add mining node to distribution

### PR DESCRIPTION
**Pull request by StriderDM**
## Description
Disable toggle_mining command in the base node.
Add mining node to startup scripts.
Update scripts to start mining node instead of using the enable_mining flag.
Add mining node to distribution/installer for osx, linux, mac.

## Types of changes
* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [x] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:
* [x] I'm merging against the `development` branch.
* [x] I ran `cargo-fmt --all` before pushing.
* [ ] I ran `cargo test` successfully before submitting my PR.
* [x] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by hansieodendaal** [comment]
Looking good reviewing the changes; will run a full installer/tarball creation with installation test for Windows and Ubuntu.

**Notes:** 
- If you could possibly solve the Ubuntu start scripts to verify if Tor is running that would be awesome; the previous attempt did not work properly for both the on-click-execute-all and single execution options and was removed a while back.
- I assume the standalone miner shortcut's icon is also pointing to this? `Source: "tari_logo_purple.ico"; DestDir: "{userdocs}\..\temp\tari_icons";`

**Review by stringhandler — APPROVED** [review]
Nice

**Comment by leet4tari** [comment]
A little late to comment on this, but there are shell scripts that have been includes as binary files ... Now double checking and see them as empty files? ```applications/tari_mining_node/osx/start_tari_mining_node.sh```, ```applications/tari_mining_node/ubuntu/start_tari_mining_node.sh```, ```applications/tari_mining_node/windows/start_tari_console_wallet.lnk``` ... I think they were symlinks, but something is not quite right there?

**Comment by StriderDM** [comment]
@leet4tari They're not empty files. The two `start_tari_mining_node.sh` files are aliases and the `start_tari_console_wallet.lnk` is a windows shortcut. If you open them with an  editor like Atom do they still display as being empty?

**Comment by StriderDM** [comment]
@hansieodendaal For your notes. Didn't know the first point was an issue on ubuntu. For the second point it should be, didn't change anything regarding the shortcuts, used what already existed for that.

**Comment by leet4tari** [comment]
Looking in GitHub - https://github.com/StriderDM/tari/blob/21b50bc29e43c148284a52c9e55c8023aa9601d5/applications/tari_mining_node/osx/start_tari_mining_node.sh is empty/binary and not a symbolic link ... **Alias** is what I think Microsoft calls it?
Screenshot 2021-02-16 at 14 12 41

verse https://github.com/StriderDM/tari/blob/21b50bc29e43c148284a52c9e55c8023aa9601d5/applications/tari_base_node/osx/start_all
Screenshot 2021-02-16 at 14 12 57

I can't say anything about the Windows Alias to the ```.lnk``` file.

**Comment by StriderDM** [comment]
@leet4tari Fixed here:
https://github.com/tari-project/tari/pull/2652

Credit to @hansieodendaal

**Comment by leet4tari** [comment]
Still looks wrong in GitHub
Screenshot 2021-02-17 at 08 36 50

Did a git clone and looks like symlinks on my OSX. Maybe just some sort of glitch in GitHub.

Not tested the scripts myself.

**Comment by leet4tari** [comment]
Looked up git usage and symlinks ... Not sure why we using the symlinks, but might be an idea either to agree on and how they used. Reading https://stackoverflow.com/questions/954560/how-does-git-handle-symbolic-links seems like a can of worms we could avoid.

**Comment by StriderDM** [comment]
@leet4tari I have seen that stackoverflow link. You can also have a look here https://mokacoding.com/blog/symliks-in-git/

They were created with the following:
```
ln -s ./runtime/start_tari_mining_node.sh start_tari_mining_node
```

**Comment by leet4tari** [comment]
Still looks broken in the web view on GitHub and both the articles show a folder with an arrow, that is what I expect from a symlink, but our repo shows a bin file, which we can't open using a browser via the web. I am just pointing this out, mostly to keep in mind.

Could be how Windows deals with symlinks or maybe a change to git.core settings. This is just a warning.

**Pull request merged**
