### PR TITLE
Removed tari_broadcast_channel and unused deps from tari_core

### PR DESCRIPTION
**Pull request by sdbondi**
## Description

Replaced tari_broadcast_channel with tokio broadcast channel.

Dependencies removed from tari_core:
arrayref
base64
cfg-if
config (moved to dev-dependencies)
crossbeam-channel
lazy_static
rmp-serde
tower_service

## Motivation and Context

tari_broadcast_channel is deprecated. 

## How Has This Been Tested?

Existing tests pass

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [x] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [x] I'm merging against the `development` branch.
* [x] I ran `cargo-fmt --all` before pushing.
* [x] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by philipr-za — DISMISSED** [review]
🎉

**Comment by delta1** [comment]
LGTM - `cargo test` was successful

**Review by SWvheerden — DISMISSED** [review]
LGTM

**Comment by sdbondi** [comment]
Resolved conflicts

**Comment by sdbondi** [comment]
Resolved conflicts

**Comment by sdbondi** [comment]
Updated branch so that clippy can pass

**Pull request merged**
