### PR TITLE
[chore] Update prettier paths

### PR DESCRIPTION
**Pull request by delta1**
Prettier was missing some paths, also ran a cargo fmt.

re: #2820

### CODE REVIEW

**Review by sdbondi — APPROVED** [review]
Thanks

**Comment by delta1** [comment]
No worries!

**Review by sdbondi — CHANGES_REQUESTED** [review]
I `npm run fmt` it now with `.` and it started formatting temp json files (takes a while and is a little annoying).
Think we should still restrict it to js, I was missing the quote marks for the globs
```
    "fmt": "prettier -w '**/*.js'",
    "check-fmt": "prettier -c '**/*.js'"
```

**Comment by delta1** [comment]
@sdbondi I added a `.prettierignore` which should ignore the whole temp folder - did it not?

**Comment by sdbondi** [comment]
Ah ok that'll work as well, no this was for a PR in another branch.

**Review by sdbondi — DISMISSED** [review]

**Comment by delta1** [comment]
Cool, resolving conflicts now

**Review by sdbondi — APPROVED** [review]

**Review by stringhandler — APPROVED** [review]

**Pull request merged**
