### PR TITLE
fix: make logging less noisy

### PR DESCRIPTION
**Pull request by stringhandler**
Description
---
Remove logging of errors from tracing instrument macros.

Motivation and Context
---
Was reported as making the base node unusable. Hopefully we are not swallowing important information, but probably the right choice

How Has This Been Tested?
---
Manually

> ~~Note: This PR is based on #3266 to enable compilation without SQLite installed~~

### CODE REVIEW

**Review by philipr-za — DISMISSED** [review]
Reviewed the `make logging of errors less noisy` commit and it looks good to me. 

I think this is a case that dialing is a behaviour that is expected to fail under normal operation which would mean its not a show stopping error that deserves to appear in the main UI. Should definitely still be visible in the logs/tracing though.

**Comment by stringhandler** [comment]
Yeah I think the best situation would be logging the error higher up in situations where you definitely want the dial to succeed. In most cases the extra logging was due to the `err` member in the `#[instrument()]` attribute, which is very useful, but you can't specify the logging level

**Review by SWvheerden — DISMISSED** [review]
LGTM,
I only reviewed the last commit as the rest looks like a duplicate of PR#3266

**Review by hansieodendaal — DISMISSED** [review]
LGTM (not tested)
Reviewed the `make logging of errors less noisy` commit

**Comment by stringhandler** [comment]
Cherry picked to reduce noise

**Review by SWvheerden — APPROVED** [review]
LGTM

**Review by sdbondi — APPROVED** [review]

**Pull request merged**
