### PR TITLE
chore: fix ci

### PR DESCRIPTION
**Pull request by SWvheerden**
Description
---
fixes CI updating the nightly version

### CODE REVIEW

**Review by leet4tari — DISMISSED** [review]
utACK

**Review by hansieodendaal — APPROVED** [review]
ACK

**Review by hansieodendaal — COMMENTED** [review]
There is a possible issue with this test 
```
Then wallet RECEIVER has at least 1 transactions that are all TRANSACTION_STATUS_ONE_SIDED_UNCONFIRMED and not cancelled
```

**Review by hansieodendaal — COMMENTED** [review]
And an issue with this test:
```
@github-actionsgithub-actions
/ Test Results (Integration tests)
All 3 runs failed: Scenario: As a client I want to send a one-sided transaction: tests/features/WalletFFI.feature:175:5
artifacts/junit-ffi-cucumber/cucumber-output-junit.xml [took 9m 2s]
```

**Comment by hansieodendaal** [comment]
@SWvheerden, two possible issues^

**Pull request merged**
