### PR TITLE
Include orphans in target difficulty calculation

### PR DESCRIPTION
**Pull request by stringhandler**
## Description

Change the target difficulty calculation to use the hash instead of height, and in turn searches the orphan chains as well as the main chain

## Motivation and Context

To solve the target difficulty problems seen in Stibbons network

## How Has This Been Tested?

Added tests to reproduce the problem

## Checklist:

* [x] I'm merging against the `development` branch.
* [ ] I have squashed my commits into a single commit.

### CODE REVIEW

**Review by delta1 — APPROVED** [review]
Looking good

**Comment by hansieodendaal** [comment]
Hi @mikethetike, I see I was just too slow with my review, but here goes:

It looks good, however, I would like to see this test case added and if it can produce repeatable results:

```suggestion
        let (result, blocks) = test_case_handle_possible_reorg(&[
            ("A0->GB", 1, 120),   // Chain 0 at 1
            ("B0->A0", 1, 120),   // Chain 0 at 2
            ("C0->B0", 1, 120),   // Chain 0 at 3

            ("A1->C0", 2, 120),   // Chain 1 at 5
            ("B1->A1", 2, 120),   // Chain 1 at 7
            ("C1->B1", 2, 120),   // Chain 1 at 9

            ("A2->C0", 2, 120),   // Chain 2 at 5
            ("B2->A2", 2, 120),   // Chain 2 at 7
            ("C2->B2", 2, 120),   // Chain 2 at 9

            ("D2->C2", 1, 120),   // Chain 2 at 11
            ("D1->C1", 1, 120),   // Chain 1 at 11

            ("E1->D1", 1, 120),   // Chain 1 at 13
            ("E2->D2", 1, 120),   // Chain 2 at 13
        ])
```

**Review by hansieodendaal — COMMENTED** [review]
Hi @mikethetike, I see I was just too slow with my review, but here goes:

It looks good, however, I would like to see this test case added and if it can produce repeatable results:

```suggestion
        let (result, blocks) = test_case_handle_possible_reorg(&[
            ("A0->GB", 1, 120),   // Chain 0 at 1
            ("B0->A0", 1, 120),   // Chain 0 at 2
            ("C0->B0", 1, 120),   // Chain 0 at 3

            ("A1->C0", 2, 120),   // Chain 1 at 5
            ("B1->A1", 2, 120),   // Chain 1 at 7
            ("C1->B1", 2, 120),   // Chain 1 at 9

            ("A2->C0", 2, 120),   // Chain 2 at 5
            ("B2->A2", 2, 120),   // Chain 2 at 7
            ("C2->B2", 2, 120),   // Chain 2 at 9

            ("D2->C2", 1, 120),   // Chain 2 at 11
            ("D1->C1", 1, 120),   // Chain 1 at 11

            ("E1->D1", 1, 120),   // Chain 1 at 13
            ("E2->D2", 1, 120),   // Chain 2 at 13
        ])
```

**Comment by stringhandler** [comment]
Cool, nice test @hansieodendaal I'll add a follow-up PR

**Pull request merged**
