### PR TITLE
test(mining-helper): generic miner helper tests, add detection test for consensus enc changes

### PR DESCRIPTION
**Pull request by sdbondi**
Description
---
- mine a new nonce for `check_difficulty` and `check_share` tests 
- adds `detect_change_in_consensus_encoding` to detect changes in consensus encoding that require updates to pool miner code

Motivation and Context
---
Ref PR #4088 - `check_difficulty` and `check_share` tests are brittle because any change to consensus encoding causes them to fail. In that case, OutputFlags changed from a u8 to a u16. These tests now generate a new nonce and difficulty (takes ~1s on good hardware) and check that the FFI functions return matching results. This was done to eliminate the time and LOC needed to fix these tests in PRs that require changes to consensus encoding (many expected in the coming weeks/months).

`detect_change_in_consensus_encoding` was added to make it clear that code changes in a given PR require an update to the pool miner code.

How Has This Been Tested?
---
The new tests pass

### CODE REVIEW

**Review by SWvheerden — DISMISSED** [review]
LGTM
Only changes tests.

**Review by therustmonk — DISMISSED** [review]

**Review by SWvheerden — DISMISSED** [review]
LGTM

**Review by SWvheerden — DISMISSED** [review]
LGTM

**Review by stringhandler — DISMISSED** [review]

**Review by CjS77 — DISMISSED** [review]
LGTM 
UT ACK

**Review by stringhandler — APPROVED** [review]

**Pull request merged**
