### PR TITLE
WIP: fix: remove unnecessary database encryption MAC

### PR DESCRIPTION
**Pull request by AaronFeickert**
Description
---
[PR 4340](https://github.com/tari-project/tari/pull/4340) adds an unnecessary MAC.

Motivation and Context
---
The existing AES-GCM AEAD includes an authentication tag, but it does not bind to the domain. This PR binds the domain to the existing AEAD tag, and removes the unnecessary MAC. It also improves the tests.

How Has This Been Tested?
---
Existing tests are updated.

### CODE REVIEW

**Comment by AaronFeickert** [comment]
A future update might consider switching from AES-GCM to XChaCha20-Poly1305. There are few good reasons to use AES-GCM anymore.

**Comment by sdbondi** [comment]
@AaronFeickert Looks like you need to run a `cargo fmt --all`

**Review by sdbondi — DISMISSED** [review]

**Review by sdbondi — APPROVED** [review]

**Comment by sdbondi** [comment]
@AaronFeickert One last barrier to merge :/ We require [commits to be signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

You may be able to run this command to resign all commits:
git rebase --exec 'git commit --amend --no-edit -n -S' -i development

**Comment by AaronFeickert** [comment]
Superseded by [PR 4550](https://github.com/tari-project/tari/pull/4550), which uses XChaCha20-Poly1305 for better random nonce security.

**Pull request closed without merging**
