### PR TITLE
fix: replace tui with ratatui

### LINKED ISSUE #5618: RUSTSEC-2023-0049: `tui` is unmaintained; use `ratatui` instead
> `tui` is unmaintained; use `ratatui` instead

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `tui`                      |
| Version             | `0.16.0`                   |
| URL                 | [https://github.com/fdehau/tui-rs/issues/654](https://github.com/fdehau/tui-rs/issues/654) |
| Date                | 2023-08-07                         |

The [`tui`](https://crates.io/crates/tui) crate is no longer maintained.

Consider using the [`ratatui`](https://crates.io/crates/ratatui) crate instead.

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2023-0049.html) for additional details.

### PR DESCRIPTION
**Pull request by therustmonk**
Description
---
Switch from the `tui` crate to `ratatui`.

Motivation and Context
---
The tui crate is no longer actively maintained. Fixes #5618 

How Has This Been Tested?
---
CI

### CODE REVIEW

**Comment by therustmonk** [comment]
After updating the launchpad, I saw that it's an opportune moment to implement the same changes here, given today's minimal alterations.

**Review by SWvheerden — CHANGES_REQUESTED** [review]
this does not seem to work correctly:
Screenshot 2023-08-30 at 09 38 35


the transaction view works fine, but all other tabs are empty

**Comment by stringhandler** [comment]
Tested on windows, but it skips every second tab when I press left and right

**Comment by kdheepak** [comment]
On Windows, the duplicate key issue is due to a new feature in Crossterm. You want to make sure you check for the `KeyEventKind::Press` state:

```diff
-  CrosstermEvent::Key(e) => tx.send(Event::Key(e)),
+  CrosstermEvent::Key(key) => {
+      if key.kind == KeyEventKind::Press {
+        tx.send(Event::Key(key));
+      }
+    },
```

For relevant information here: https://github.com/ratatui-org/ratatui/issues/347 and here: https://ratatui.rs/faq/#why-am-i-getting-duplicate-key-events-on-windows

**Pull request closed without merging**
