### PR TITLE
fix: exclude libtor from windows build

### PR DESCRIPTION
**Pull request by sdbondi**
Description
---

Motivation and Context
---

How Has This Been Tested?
---

### CODE REVIEW

**Comment by delta1** [comment]
lol for devs on windows

**Comment by sdbondi** [comment]
libtor isnt built on windows

**Comment by sdbondi** [comment]
Matrix builds passing https://github.com/sdbondi/tari/actions/runs/3008941799

**Comment by AaronFeickert** [comment]
Fixes `cargo check` on my local Linux machine too.

**Review by stringhandler — APPROVED** [review]

**Pull request merged**
