### PR TITLE
Remove generated proto files from tari_core

### PR DESCRIPTION
**Pull request by sdbondi**
## Description

Cleans up the code a bit in tari_core::proto by removing the `generated`
module. Instead of including the generated files directly, protos are
generated to the OUT_DIR and included using the `include!` macro. This
is the intended way that generated files are included, however
this would previously break intellisense in IDEs.

IDE and rust analyser support for OUT_DIR has greatly improved.
see:
https://blog.jetbrains.com/clion/2019/12/recent-updates-in-rust/
https://github.com/rust-analyzer/rust-analyzer/pull/3549

## Motivation and Context

This is the "standard" way to include generated files.
Slightly different generated output on windows/mac/linux is annoying when the code is under source control.
At least one user had issues building because write permissions are needed in the source dir, although it's not clear that this will fix that particular issue.

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [ ] I'm merging against the `development` branch.
* [ ] I ran `cargo-fmt --all` before pushing.
* [ ] I ran `cargo test` successfully before submitting my PR.
* [ ] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by delta1** [comment]
Nice one, testing

**Review by delta1 — APPROVED** [review]
LGTM

**Review by stringhandler — APPROVED** [review]
Nice

**Comment by stringhandler** [comment]
Related to #2579 but there may be more files that need to be fixed. Should also speed up windows compiles

**Pull request merged**
