### PR TITLE
chore: delete some unneed, unsafe functions

### PR DESCRIPTION
**Pull request by stringhandler**
Description
---
Remove unneed and unsafe pieces of code

I am not sure what the intention was for `ScriptCommitment`, but it seems to be unused.

### CODE REVIEW

**Comment by AaronFeickert** [comment]
Will new wallet sign/verify functions be created once the new [signature API](https://github.com/tari-project/tari-crypto/pull/145) is completed? See [this comment](https://github.com/tari-project/tari/issues/4878#issuecomment-1303951307).

**Comment by AaronFeickert** [comment]
Aside from the above question, LGTM.

**Comment by CjS77** [comment]
ACK

**Review by CjS77 — APPROVED** [review]
LGTM

**Pull request merged**
