### PR TITLE
Update `test_transaction_cancellation_sqlite_db` to track down CI flakiness

### PR DESCRIPTION
**Pull request by philipr-za**
## Description
Added a check for the cancellation event which will help nail down where the test fails on CI. The test is not using a real comms stack and the operation its conducting is not time intensive so I cannot understand what is different on CI compared to local.

## How Has This Been Tested?
Is a test update

## Types of changes

* [x] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [x] I'm merging against the `development` branch.
* [x] I ran `cargo-fmt --all` before pushing.
* [ ] I ran `cargo test` successfully before submitting my PR.
* [ ] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by delta1** [comment]
Nice I'll check this out now - I have had this error a number of times locally even, so it's pretty random and not just related to CI

**Comment by hansieodendaal** [comment]
> 
> 
> Nice I'll check this out now - I have had this error a number of times locally even, so it's pretty random and not just related to CI

ditto

**Comment by philipr-za** [comment]
> > Nice I'll check this out now - I have had this error a number of times locally even, so it's pretty random and not just related to CI
> 
> ditto

I will try run the whole test suite then, running the test on its own 100 times in a row showed no failures.

**Review by hansieodendaal — APPROVED** [review]
LGTM

**Pull request merged**
