### PR TITLE
Fix double spend test.

### PR DESCRIPTION
**Pull request by Cifko**
The problem was that TransactionInput has now new fields, including signature which is never equal because of the random nonce.

## Description
Change the PartialEq trait for TransactionInput to only compare commitment (UTXO).

### CODE REVIEW

**Comment by delta1** [comment]
Is this for the `Mempool.feature` "Double spend" integration test?

**Review by delta1 — APPROVED** [review]
LGTM, tested the "Double spend" integration test which is now working 👍 

@philipr-za can you give a 👀 please?

**Review by stringhandler — COMMENTED** [review]
I think this is definitely problem, so nice find, but I don't agree with the solution you have proposed.

I think this is better solved by fixing the code  in the mempool to look at the commitment instead of whether inputs are equal. Two inputs are not strictly equal if they are spending the same commitment, because there may be two inputs spending the same output, but with entirely different script inputs. 
For example, consider [the timelocked example in rfc](https://rfc.tari.com/RFC-0202_TariScriptOpcodes.html#time-locked-contract). In this case there may be an input from Bob and an input from Alice that take different script inputs and signatures to spend the input.

**Review by SWvheerden — APPROVED** [review]
While this might I would caution against this way as we are now saying that 2 `TransactionInputs` are equal if their commitments are the same. 

For example, if we have 2 `TransactionInput` with the same commitment, and change the one's feature flags, we would expect that `TransactionInput_1 =! TransactionInput_2`. 
But with this PR `TransactionInput_1 == TransactionInput_2`

If this is the problem for the double-spend, perhaps we should create another method in TransactionInput to only do this comparison or manually do the comparison in the mempool where this occurs.

**Comment by delta1** [comment]
Cool, that's the feedback I was looking for thanks @mikethetike and @SWvheerden.

**Comment by delta1** [comment]
Sorry wrong button

**Comment by Cifko** [comment]
Ok, I put back the derive trait of PartialEq for TransactionInput. And I changed how mempool find duplicates. The test is ok. Can you please confirm if this is the way to go? Thanks.

**Review by stringhandler — APPROVED** [review]
utACK

Nice

**Review by delta1 — APPROVED** [review]
utACK

**Pull request merged**
