### PR TITLE
chore(ci): fix ci

### PR DESCRIPTION
**Pull request by SWvheerden**
Description
---
Fixes the CI
Updates the self hosted to a newer version

### CODE REVIEW

**Comment by AaronFeickert** [comment]
Looks like CI still [fails](https://github.com/tari-project/tari/actions/runs/4861243058/jobs/8667092692?pr=5362#step:6:16).

**Review by AaronFeickert — APPROVED** [review]
Looks like this fixes the failures noted in [issue 5361](https://github.com/tari-project/tari/issues/5361). Some integration tests fail, but that doesn't seem like a regression given the flaky nature of those tests.

**Comment by SWvheerden** [comment]
yeah its the same old flaky tests noted here: https://github.com/tari-project/tari/issues/5198

**Review by stringhandler — APPROVED** [review]
Happy, but 74 minutes on the CI seems wrong

**Pull request merged**
